version: "3.3"

services:
  screen_service:
    build: .
    restart: always
    image: fapsdemonstratorview2_screen_service:latest
    environment:
      - PORT:8090
    ports:
      - "8090:8090"
    networks: 
      - backend

networks:
  backend:
    driver: "overlay"
    attachable: true
